### ISSUE TITLE
Folder name too long

### ISSUE THREAD

**Issue by AinaEmmanuel** [dhanrajdc7/Code-Overflow#1656]
The name of a folder by [guptamuskan988](https://github.com/dhanrajdc7/Code-Overflow/tree/main/%23include%20%3Cmath.h%3E%20%23include%20%3Cstdio.h%3E%20int%20convert(long%20long%20n)%3B%20int%20main()%20%7B%20%20%20%20%20long%20long%20n%3B%20%20%20%20%20printf(%22Enter%20a%20binary%20number:%20%22)%3B%20%20%20%20%20scanf(%22%25lld%22%2C%20%26n)%3B%20%20%20%20%20printf(%22%25lld%20in%20binary%20%3D%20%25d%20in%20decimal%22%2C%20n%2C%20convert(n))%3B%20%20%20%20%20return%200%3B%20%7D%20%20int%20convert(long%20long%20n)%20%7B%20%20%20%20%20int%20dec%20%3D%200%2C%20i%20%3D%200%2C%20rem%3B%20%20%20%20%20while%20(n%20!%3D%200)%20%7B%20%20%20%20%20%20%20%20%20rem%20%3D%20n%20%25%2010%3B%20%20%20%20%20%20%20%20%20n) is too long, thereby making it difficult to clone the entire repository

**Comment by dhanrajdc7** [comment]
Hi!
Don't clone the whole repo.
You can add a file directly.

Watch this Tutorial: https://youtu.be/qEQB9BjqotM
