### ISSUE TITLE
Can't clone to local: File name too long

### ISSUE THREAD

**Issue by ridwankustanto** [dhanrajdc7/Code-Overflow#889]
Hi, I try to fork and clone this project, but it's failed bcs of file name too long.

![image](https://user-images.githubusercontent.com/19152005/96358266-7f313b00-112f-11eb-8c3b-c7877b401740.png)

I believe this happened because of this folder in your repo:

![image](https://user-images.githubusercontent.com/19152005/96358284-a8ea6200-112f-11eb-9143-d132054867cd.png)

what do you think? @dhanrajdc7

**Comment by dhanrajdc7** [comment]
Hi!
You can add a new file or upload your file on Repo

**Comment by ridwankustanto** [comment]
Ohh I see, okaay
